### ISSUE TITLE
Brunch ?! seems to not work

### ISSUE THREAD

**Issue by jeremieca** [deliciousinsights/brunch-guide#32]
Hello,

Maybe I have a mistake but this configuration does not work... 
app.js contains tests/unit/spec.js and tests/func/spec.js and I don't understand why !

```
  files:
    javascripts:
      joinTo:
        'app.js': /(?!tests)/
        'test-unit.js': /\/tests\/unit\//
        'test-func.js': /\/tests\/func\//
```

Thanks !!!
